//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVP.UAVPSet.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAVP.UAVPSet.Resources.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fly as + (0) ähnelt.
        /// </summary>
        internal static string bit0 {
            get {
                return ResourceManager.GetString("bit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fly as X (1) ähnelt.
        /// </summary>
        internal static string bit01 {
            get {
                return ResourceManager.GetString("bit01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die throttle on 1 (0) ähnelt.
        /// </summary>
        internal static string bit1 {
            get {
                return ResourceManager.GetString("bit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die throttle on 3 (1) ähnelt.
        /// </summary>
        internal static string bit11 {
            get {
                return ResourceManager.GetString("bit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die normal mode (0) ähnelt.
        /// </summary>
        internal static string bit2 {
            get {
                return ResourceManager.GetString("bit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die integration mode (1) ähnelt.
        /// </summary>
        internal static string bit21 {
            get {
                return ResourceManager.GetString("bit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll / Nick 1:1 (0) ähnelt.
        /// </summary>
        internal static string bit3 {
            get {
                return ResourceManager.GetString("bit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll / Nick decreased by half (1) ähnelt.
        /// </summary>
        internal static string bit31 {
            get {
                return ResourceManager.GetString("bit31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pos. Impulse (0) ähnelt.
        /// </summary>
        internal static string bit4 {
            get {
                return ResourceManager.GetString("bit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neg. Impulse (1) ähnelt.
        /// </summary>
        internal static string bit41 {
            get {
                return ResourceManager.GetString("bit41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write sucessfully! ähnelt.
        /// </summary>
        internal static string burnPicOk {
            get {
                return ResourceManager.GetString("burnPicOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnected! ähnelt.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot the UAVP-Board! ähnelt.
        /// </summary>
        internal static string flashInfo {
            get {
                return ResourceManager.GetString("flashInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected! ähnelt.
        /// </summary>
        internal static string listviewConnected {
            get {
                return ResourceManager.GetString("listviewConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Set 1 ähnelt.
        /// </summary>
        internal static string paraSet1 {
            get {
                return ResourceManager.GetString("paraSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Set 2 ähnelt.
        /// </summary>
        internal static string paraSet2 {
            get {
                return ResourceManager.GetString("paraSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Set 1 (ACTIV) ähnelt.
        /// </summary>
        internal static string paraSetAktiv1 {
            get {
                return ResourceManager.GetString("paraSetAktiv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Set 2 (ACTIV) ähnelt.
        /// </summary>
        internal static string paraSetAktiv2 {
            get {
                return ResourceManager.GetString("paraSetAktiv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected! ähnelt.
        /// </summary>
        internal static string picConnected {
            get {
                return ResourceManager.GetString("picConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flash the PIC? PIC 16F876A is not supported! ähnelt.
        /// </summary>
        internal static string savePicBurn {
            get {
                return ResourceManager.GetString("savePicBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write Line: ähnelt.
        /// </summary>
        internal static string writeLine {
            get {
                return ResourceManager.GetString("writeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die from ähnelt.
        /// </summary>
        internal static string writeMax {
            get {
                return ResourceManager.GetString("writeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully write! ähnelt.
        /// </summary>
        internal static string writeOk {
            get {
                return ResourceManager.GetString("writeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die write Parameter: ähnelt.
        /// </summary>
        internal static string writeParameter {
            get {
                return ResourceManager.GetString("writeParameter", resourceCulture);
            }
        }
    }
}
