//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVP.UAVPSet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAVP.UAVPSet.Resources.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Mode.
        /// </summary>
        internal static string bit0 {
            get {
                return ResourceManager.GetString("bit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Mode.
        /// </summary>
        internal static string bit01 {
            get {
                return ResourceManager.GetString("bit01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel 1.
        /// </summary>
        internal static string bit1 {
            get {
                return ResourceManager.GetString("bit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel 3.
        /// </summary>
        internal static string bit11 {
            get {
                return ResourceManager.GetString("bit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode 1.
        /// </summary>
        internal static string bit2 {
            get {
                return ResourceManager.GetString("bit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode 2.
        /// </summary>
        internal static string bit21 {
            get {
                return ResourceManager.GetString("bit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd Channels.
        /// </summary>
        internal static string bit3 {
            get {
                return ResourceManager.GetString("bit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Channels.
        /// </summary>
        internal static string bit31 {
            get {
                return ResourceManager.GetString("bit31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        internal static string bit4 {
            get {
                return ResourceManager.GetString("bit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        internal static string bit41 {
            get {
                return ResourceManager.GetString("bit41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barometer.
        /// </summary>
        internal static string bit5 {
            get {
                return ResourceManager.GetString("bit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS (Caution).
        /// </summary>
        internal static string bit51 {
            get {
                return ResourceManager.GetString("bit51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string bit6 {
            get {
                return ResourceManager.GetString("bit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string bit61 {
            get {
                return ResourceManager.GetString("bit61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string bit7 {
            get {
                return ResourceManager.GetString("bit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string bit71 {
            get {
                return ResourceManager.GetString("bit71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write sucessfull!.
        /// </summary>
        internal static string BurnPICOk {
            get {
                return ResourceManager.GetString("BurnPICOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected!.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot PIC!.
        /// </summary>
        internal static string flashInfo {
            get {
                return ResourceManager.GetString("flashInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        internal static string listviewConnected {
            get {
                return ResourceManager.GetString("listviewConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set 1.
        /// </summary>
        internal static string paraSet1 {
            get {
                return ResourceManager.GetString("paraSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set 2.
        /// </summary>
        internal static string paraSet2 {
            get {
                return ResourceManager.GetString("paraSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set 1 (ACTIVE).
        /// </summary>
        internal static string paraSetAktiv1 {
            get {
                return ResourceManager.GetString("paraSetAktiv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set 2 (ACTIVE).
        /// </summary>
        internal static string paraSetAktiv2 {
            get {
                return ResourceManager.GetString("paraSetAktiv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        internal static string picConnected {
            get {
                return ResourceManager.GetString("picConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the PIC? *Note the PIC 16F876A is not supported! PIC 16F876, 18F2520 and 18F2620 are supported.  Please select the correct firmware for the PIC when burning or updating.   :).
        /// </summary>
        internal static string savePicBurn {
            get {
                return ResourceManager.GetString("savePicBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Line:.
        /// </summary>
        internal static string writeLine {
            get {
                return ResourceManager.GetString("writeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string writeMax {
            get {
                return ResourceManager.GetString("writeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull write!.
        /// </summary>
        internal static string writeOk {
            get {
                return ResourceManager.GetString("writeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Parameter:.
        /// </summary>
        internal static string writeParameter {
            get {
                return ResourceManager.GetString("writeParameter", resourceCulture);
            }
        }
    }
}
